window.ETAPPENINFO = {
   "01 Steeg-Weissenbach.gpx": {
      "Titel": "Biketrail-Etappe 1: Steeg-Weissenbach",
      "Ausgangspunkt": "Steeg",
      "Endpunkt": "Weissenbach",
      "Laenge (in km)": "44",
      "Fahrzeit (in Stunden)": "4,5",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeter bergauf": 200,
      "Hoehenmeter bergab": 420,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-steeg-weissenbach"
   },
   "02 Weissenbach-Tannheim.gpx": {
      "Titel": "Biketrail-Etappe 2: Weissenbach-Tannheim",
      "Ausgangspunkt": "Weissenbach",
      "Endpunkt": "Tannheim",
      "Laenge (in km)": "17,1",
      "Fahrzeit (in Stunden)": "2,25",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 400,
      "Hoehenmeter bergab": 190,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-weissenbach-tannheim"
   },
   "03 Tannheim-Reutte.gpx": {
      "Titel": "Biketrail-Etappe 3: Tannheim-Reutte",
      "Ausgangspunkt": "Tannheim",
      "Endpunkt": "Reutte",
      "Laenge (in km)": "44",
      "Fahrzeit (in Stunden)": "4",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 500,
      "Hoehenmeter bergab": 590,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-tannheim-reutte"
   },
   "04 Weissenbach-Reutte.gpx": {
      "Titel": "Biketrail-Etappe 4: Weissenbach-Reutte",
      "Ausgangspunkt": "Weissenbach",
      "Endpunkt": "Reutte",
      "Laenge (in km)": "7,1",
      "Fahrzeit (in Stunden)": "1",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeter bergauf": 160,
      "Hoehenmeter bergab": 50,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-weissenbach-reutte"
   },
   "05 Reutte-Ehrwald.gpx": {
      "Titel": "Biketrail-Etappe 5: Reutte-Ehrwald",
      "Ausgangspunkt": "Reutte",
      "Endpunkt": "Ehrwald",
      "Laenge (in km)": "18,8",
      "Fahrzeit (in Stunden)": "2",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeter bergauf": 280,
      "Hoehenmeter bergab": 285,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-reutte-ehrwald"
   },
   "06 Ehrwald-Scharnitz.gpx": {
      "Titel": "Biketrail-Etappe 6: Ehrwald-Scharnitz",
      "Ausgangspunkt": "Ehrwald",
      "Endpunkt": "Scharnitz",
      "Laenge (in km)": "40",
      "Fahrzeit (in Stunden)": "4",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 990,
      "Hoehenmeter bergab": 1200,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-ehrwald-scharnitz"
   },
   "07 Scharnitz-Achensee.gpx": {
      "Titel": "Biketrail-Etappe 7: Scharnitz - Achensee",
      "Ausgangspunkt": "Scharnitz",
      "Endpunkt": "Achensee",
      "Laenge (in km)": "61,5",
      "Fahrzeit (in Stunden)": "6",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeter bergauf": 1850,
      "Hoehenmeter bergab": 1880,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-scharnitz-achensee"
   },
   "08 Achensee-Kaiserhaus.gpx": {
      "Titel": "Biketrail-Etappe 8: Achensee - Kaiserhaus",
      "Ausgangspunkt": "Achensee",
      "Endpunkt": "Kaiserhaus",
      "Laenge (in km)": "56",
      "Fahrzeit (in Stunden)": "5",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeter bergauf": 1460,
      "Hoehenmeter bergab": 1660,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-achensee-kaiserhaus"
   },
   "09 Kaiserhaus-Kufstein.gpx": {
      "Titel": "Biketrail-Etappe 9: Kaiserhaus � Kufstein ",
      "Ausgangspunkt": "Kaiserhaus",
      "Endpunkt": "Kufstein",
      "Laenge (in km)": "31,5",
      "Fahrzeit (in Stunden)": "3,25",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 540,
      "Hoehenmeter bergab": 780,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-kaiserhaus-kufstein"
   },
   "10 Kufstein-Koessen.gpx": {
      "Titel": "Biketrail-Etappe 10: Kufstein - Koessen ",
      "Ausgangspunkt": "Kufstein",
      "Endpunkt": "Koessen",
      "Laenge (in km)": "33,8",
      "Fahrzeit (in Stunden)": "3",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 770,
      "Hoehenmeter bergab": 660,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-kufstein-koessen"
   },
   "11 Koessen-Kitzbuehel.gpx": {
      "Titel": "Biketrail-Etappe 11: Koessen - Kitzbuehel",
      "Ausgangspunkt": "Koessen",
      "Endpunkt": "Kitzbuehel",
      "Laenge (in km)": "56",
      "Fahrzeit (in Stunden)": "7",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeter bergauf": 1900,
      "Hoehenmeter bergab": 1730,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-koessen-kitzbuehel"
   },
   "12 Variante Pillersee.gpx": {
      "Titel": "Biketrail-Etappe 12: Variante Pillersee ",
      "Ausgangspunkt": "Erpfendorf",
      "Endpunkt": "Muehlbach",
      "Laenge (in km)": "42",
      "Fahrzeit (in Stunden)": "4",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 850,
      "Hoehenmeter bergab": 770,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-variante-pillersee"
   },
   "13 Kitzbühel-Westendorf.gpx": {
      "Titel": "Biketrail-Etappe 13: Kitzbuehel - Westendorf ",
      "Ausgangspunkt": "Kitzbuehel",
      "Endpunkt": "Westendorf",
      "Laenge (in km)": "15,5",
      "Fahrzeit (in Stunden)": "1,75",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeter bergauf": 150,
      "Hoehenmeter bergab": 150,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-kitzbuehel-westendorf"
   },
   "14 Westendorf-Alpbach.gpx": {
      "Titel": "Biketrail-Etappe 14: Westendorf - Alpbach ",
      "Ausgangspunkt": "Westendorf",
      "Endpunkt": "Alpbach",
      "Laenge (in km)": "36,5",
      "Fahrzeit (in Stunden)": "4,5",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 1300,
      "Hoehenmeter bergab": 1100,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-westendorf-alpbach"
   },
   "15 Alpbach-Zell.gpx": {
      "Titel": "Biketrail-Etappe 15: Alpbach- Zell",
      "Ausgangspunkt": "Alpbach",
      "Endpunkt": "Zell",
      "Laenge (in km)": "43,5",
      "Fahrzeit (in Stunden)": "5",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 1150,
      "Hoehenmeter bergab": 1550,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-alpbach-zell"
   },
   "16 Zell-Achensee.gpx": {
      "Titel": "Biketrail-Etappe 16: Zell - Achensee ",
      "Ausgangspunkt": "Zell",
      "Endpunkt": "Achensee",
      "Laenge (in km)": "36,5",
      "Fahrzeit (in Stunden)": "3",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeter bergauf": 580,
      "Hoehenmeter bergab": 220,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-zell-achensee"
   },
   "17 Zell-Mayrhofen.gpx": {
      "Titel": "Biketrail-Etappe 17: Zell - Mayrhofen ",
      "Ausgangspunkt": "Zell",
      "Endpunkt": "Mayrhofen",
      "Laenge (in km)": "8,8",
      "Fahrzeit (in Stunden)": "1",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeter bergauf": 30,
      "Hoehenmeter bergab": 90,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-zell-mayrhofen"
   },
   "18 Mayrhofen-Lanersbach.gpx": {
      "Titel": "Biketrail-Etappe 18: Mayrhofen - Lanersbach ",
      "Ausgangspunkt": "Mayhofen",
      "Endpunkt": "Lanersbach",
      "Laenge (in km)": "14,5",
      "Fahrzeit (in Stunden)": "3",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 900,
      "Hoehenmeter bergab": 280,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-mayrhofen-lanersbach"
   },
   "19 Lanersbach-Weerberg.gpx": {
      "Titel": "Biketrail-Etappe 19: Lanersbach - Geiseljoch - Weerberg ",
      "Ausgangspunkt": "Lanersbach",
      "Endpunkt": "Weerberg",
      "Laenge (in km)": "28",
      "Fahrzeit (in Stunden)": "5",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeter bergauf": 1090,
      "Hoehenmeter bergab": 1480,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-lanersbach-geiseljoch-weerberg"
   },
   "20 Weerberg-Windegg.gpx": {
      "Titel": "Biketrail-Etappe 20: Weerberg - Windegg",
      "Ausgangspunkt": "Weerberg",
      "Endpunkt": "Windegg",
      "Laenge (in km)": "22",
      "Fahrzeit (in Stunden)": "4,5",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 940,
      "Hoehenmeter bergab": 630,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-weerberg-windegg"
   },
   "21 Windegg-Matrei.gpx": {
      "Titel": "Biketrail-Etappe 21: Windegg - Matrei",
      "Ausgangspunkt": "Windegg",
      "Endpunkt": "Matreier Tauernhaus",
      "Laenge (in km)": "27",
      "Fahrzeit (in Stunden)": "3",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 520,
      "Hoehenmeter bergab": 720,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-windegg-matrei"
   },
   "22 Matrei-Mieders.gpx": {
      "Titel": "Biketrail-Etappe 22: Matrei - Mieders",
      "Ausgangspunkt": "Matrei",
      "Endpunkt": "Mieders",
      "Laenge (in km)": "13",
      "Fahrzeit (in Stunden)": "3",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 740,
      "Hoehenmeter bergab": 740,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-matrei-maria-waldrast-mieders"
   },
   "23 Mieders-Mutters.gpx": {
      "Titel": "Biketrail-Etappe 23: Mieders - Mutters ",
      "Ausgangspunkt": "Mieders",
      "Endpunkt": "Mutters",
      "Laenge (in km)": "20",
      "Fahrzeit (in Stunden)": "2",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 900,
      "Hoehenmeter bergab": 1030,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-mieders-mutters"
   },
   "24 Mutters-Sellrain.gpx": {
      "Titel": "Biketrail-Etappe 24: Mutters - Sellrain ",
      "Ausgangspunkt": "Mutters",
      "Endpunkt": "Sellrain",
      "Laenge (in km)": "16,7",
      "Fahrzeit (in Stunden)": "1",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeter bergauf": 415,
      "Hoehenmeter bergab": 310,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-mutters-sellrain"
   },
   "25 Sellrain-Oetz.gpx": {
      "Titel": "Biketrail-Etappe 25: Sellrain - Kuehtai - Oetz ",
      "Ausgangspunkt": "Sellrain",
      "Endpunkt": "Oetz",
      "Laenge (in km)": "34,6",
      "Fahrzeit (in Stunden)": "3",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 1110,
      "Hoehenmeter bergab": 1270,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-sellrain-kuehtai-oetz"
   },
   "26 Oetz-Imst.gpx": {
      "Titel": "Biketrail-Etappe 26: Oetz - Imst",
      "Ausgangspunkt": "Oetz",
      "Endpunkt": "Imst",
      "Laenge (in km)": "14,6",
      "Fahrzeit (in Stunden)": "1",
      "Schwierigkeitsgrad": "leicht",
      "Hoehenmeter bergauf": 215,
      "Hoehenmeter bergab": 280,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-oetz-imst"
   },
   "27 Imst-Wenns.gpx": {
      "Titel": "Biketrail-Etappe 27: Imst - Venetalm - Wenns ",
      "Ausgangspunkt": "Imst",
      "Endpunkt": "Wenns",
      "Laenge (in km)": "21,9",
      "Fahrzeit (in Stunden)": "2",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeter bergauf": 1230,
      "Hoehenmeter bergab": 965,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-imst-venetalm-wenns"
   },
   "28 Wenns-Landeck.gpx": {
      "Titel": "Biketrail-Etappe 28: Wenns - Pillerhoehe - Landeck ",
      "Ausgangspunkt": "Wenns",
      "Endpunkt": "Landeck",
      "Laenge (in km)": "18,7",
      "Fahrzeit (in Stunden)": "1",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 630,
      "Hoehenmeter bergab": 880,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-wenns-pillerhoehe-landeck"
   },
   "29 Landeck-Ischgl.gpx": {
      "Titel": "Biketrail-Etappe 29: Landeck - Ischgl ",
      "Ausgangspunkt": "Landeck",
      "Endpunkt": "Ischgl",
      "Laenge (in km)": "33",
      "Fahrzeit (in Stunden)": "3",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeter bergauf": 1250,
      "Hoehenmeter bergab": 690,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-landeck-ischgl"
   },
   "30 Ischgl-St.Anton.gpx": {
      "Titel": "Biketrail-Etappe 30: Ischgl - St. Anton ",
      "Ausgangspunkt": "Ischgl",
      "Endpunkt": "St. Anton",
      "Laenge (in km)": "41,8",
      "Fahrzeit (in Stunden)": "4",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeter bergauf": 1290,
      "Hoehenmeter bergab": 1200,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-ischgl-st-anton"
   },
   "31 St.Anton-Steeg.gpx": {
      "Titel": "Biketrail-Etappe 31: St. Anton - Steeg ",
      "Ausgangspunkt": "St. Anton",
      "Endpunkt": "Steeg",
      "Laenge (in km)": "35,1",
      "Fahrzeit (in Stunden)": "3",
      "Schwierigkeitsgrad": "mittelschwierig",
      "Hoehenmeter bergauf": 750,
      "Hoehenmeter bergab": 1080,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-st-anton-steeg"
   },
   "32 Imst-Ehrwald.gpx": {
      "Titel": "Biketrail-Etappe 32: Imst - Marienbergjoch - Ehrwald ",
      "Ausgangspunkt": "Imst",
      "Endpunkt": "Ehrwald",
      "Laenge (in km)": "37,1",
      "Fahrzeit (in Stunden)": "3",
      "Schwierigkeitsgrad": "schwierig",
      "Hoehenmeter bergauf": 1380,
      "Hoehenmeter bergab": 1100,
      "Info": "http://www.tirol.at/reisefuehrer/sport/radfahren/biketouren/a-bike-trail-tirol-imst-marienbergjoch-ehrwald"
   }
};